name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
      
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/simple-cicd:latest
    - name: Push to Dockerhub
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/simple-cicd:latest


               